apiVersion: v1
kind: Pod
metadata:
  name: python-client
spec:
  restartPolicy: OnFailure
  containers:
  - image: python:latest
    name: python
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        eks.amazonaws.com/vgpu: 1
