apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  restartPolicy: OnFailure
  containers:
  - image: nvidia/cuda:latest
    name: pod1-ctr
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        eks.amazonaws.com/vgpu: 2
